# src/dsl/ast_nodes.py
#
# Internal representation of a WorkflowSynth workflow.
# The parser converts YAML -> WorkflowAST.
# The type_checker and taint_analyser operate on WorkflowAST.
# The adapters (n8n, LangChain) take WorkflowAST as input.

from dataclasses import dataclass, field


@dataclass
class WorkflowStep:
    """
    A single step in the workflow.

    Fields:
        id:     unique identifier for this step within the workflow.
                Generated by the LLM. Validated by the parser as a non-empty string.
        op:     DSL operator. Must be in VALID_OPS.
                The parser rejects any value outside the vocabulary.
        params: step parameters. Free dict -- each operator has its own semantics.
                The type checker validates critical fields (input, schema, etc.)
                according to the operator.
        output: name of the variable this step produces.
                Other steps can reference this name in params.input.
                May be None if the step produces no output.
    """
    id: str
    op: str
    params: dict = field(default_factory=dict)
    output: str | None = None


@dataclass
class WorkflowAST:
    """
    Complete representation of a WorkflowSynth workflow.

    Fields:
        workflow_id: unique identifier for the workflow.
        steps:       ordered list of WorkflowStep.
                     Order matters -- it defines the execution sequence.
    """
    workflow_id: str
    steps: list[WorkflowStep] = field(default_factory=list)

    def step_ids(self) -> list[str]:
        """Returns the IDs of all steps, in order."""
        return [s.id for s in self.steps]

    def output_vars(self) -> dict[str, str]:
        """
        Returns a map of output_var -> op for all steps that declare an output.
        Useful for the type_checker when verifying that params.input
        references an existing output.
        """
        return {
            s.output: s.op
            for s in self.steps
            if s.output is not None
        }
